version: '3.8'

services:
  postgres_keycloak:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev
    restart: always
    links:
      - postgres_keycloak
    ports:
      - "18080:8080"
    env_file: .env
    networks:
      - keycloak_network

volumes:
  pgdata_keycloak:
networks:
  keycloak_network:
    driver: bridge